import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Page: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <section className={styles.grid}>
          <a href='https://buy.stripe.com/28o3eLd8f3eH6DS5kk' target="blank" className={styles.card}>
            <p>
              Monthly 8 USD
            </p>
          </a>
          <a href='https://buy.stripe.com/9AQ3eLecj8z1ges3cd' target="blank" className={styles.card}>
            <p>
              Yearly 80 USD
            </p>
          </a>
          <a href='https://buy.stripe.com/test_5kA29YePw4Klc5WdQQ' target="blank" className={styles.card}>
            <p>
              TEST 80 USD
            </p>
          </a>
        </section>
      </main>
    </div>
  )
}

export default Page
