import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect } from 'react'
import styles from '../styles/Home.module.css'
import axios from 'axios';
import { priceId } from '../utils/constant'

const Checkout = () => {
  return <form action="/api/payment" method="POST">
    <input type="hidden" name="priceId" value={priceId} />
    <button type="submit">Checkout</button>
  </form>

}

const Page: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Checkout />
      </main>
    </div>
  )
}

export default Page
