import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect } from 'react'
import styles from '../styles/Home.module.css'
import axios from 'axios';

const Page: NextPage = () => {
  useEffect(()=>{
    axios.get('/api/quote?ticker=se').then(res=>{
        console.table(res.data);
    })
  }, [])
  useEffect(()=>{
    axios.get('/api/statement?ticker=se&sheet=BA').then(res=>{
        console.table(res.data.data);
    })
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        open console
      </main>
    </div>
  )
}

export default Page
